module.exports = {
  user_create_success: "Account Created Successfully",
  user_create_failed: "Account Created Failed",
  user_already_exist: "Account Already Exist",
  user_login_required: "Login Is Required",
  user_login_success: "Login Successfully",
  user_log_out_success: "Logout Successfully",
  user_not_found: "User Not Found",
  userCreationFailed: "Invalid Credential ",
  userListSuccess: "User Listed Successfully",
  userUpdateSuccess: "User Listed Successfully",
  userListFailed: "User Listed Failed",
  userUpdateFailed: "User Update Failed",
  userDeleteSuccess: "User Deleted Success",
  userDeleteFailed: "User Deleted Failed",
  roleCreatedSuccessfully: "Role Created Successfully",
  roleCreatedFailed: "Role Created Failed",
  roleListedSuccess: "Role Listed Successfully",
  roleListedFailed: "Role Listed Failed",
  roleNotFound: "No Roles Found",
  roleDeleteSuccess: "Successfully Deleted",
  roleDeleteFailed: " Roles Delete Failed",
  roleUpdatedFailed: " Roles Update Failed",
  roleUpdatedSuccess: " Roles Update Success",
  changePasswordSuccess: "Change Password Success",
  forgetPasswordSuccess: "Forget password link sent your email",
  forgetPasswordFailed: "Forget Password Failed",
  createPasswordFailed: "Create Password Failed",
  createPasswordSuccess: "Create Password Success",
  createPasswordInvalidToken: "link has expired",
  // category
  categoryCreateSuccess: "Category Create Success",
  categoryCreateFailed: "Category Create Failed",
  categoryListFailed: "Category List Failed",
  categoryListSuccess: "Category List Success",
  categoryNotFound: "Category Not Found",
  categoryUpdateSuccess: "Category Update Success",
  categoryUpdateFailed: "Category Update Failed",
  categoryDeleteSuccess: "Category Delete  Success",
  categoryDeleteFailed: "Category  Delete Failed",
};
