module.exports = {
  user_create_success: "Account Created Successfully",
  user_create_failed: "Account Created Failed",
  user_already_exist: "Account Already Exist",
  user_login_required: "Login Is Required",
  user_login_success: "Login Successfully",
  user_not_found: "User Not Found",
  userCreationFailed: "Invalid Credential ",
  userListSuccess: "User Listed Successfully",
  userListFailed: "User Listed Failed",
  userDeleteSuccess: "User Deleted Success",
  userDeleteFailed: "User Deleted Failed",
  roleCreatedSuccessfully: "Role Created Successfully",
  roleCreatedFailed: "Role Created Failed",
  roleListedSuccess: "Role Listed Successfully",
  roleListedFailed: "Role Listed Failed",
  roleNotFound: "No Roles Found",
  roleDeleteSuccess: "Successfully Deleted",
  roleDeleteFailed: " Roles Delete Failed",
  roleUpdatedFailed: " Roles Update Failed",
  roleUpdatedSuccess: " Roles Update Success",
};
